// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Yf.Api.Infrastructure;

#nullable disable

namespace Yf.Api.Infrastructure.Migrations
{
    [DbContext(typeof(YfDbContext))]
    [Migration("20260917071123_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Yf.Api.Infrastructure.Entities.AuditLog", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("varchar(48)")
                        .HasColumnName("action");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Detail")
                        .HasColumnType("json")
                        .HasColumnName("detail");

                    b.Property<string>("EmployeeNo")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("employee_no");

                    b.Property<string>("Ip")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("ip");

                    b.Property<string>("TargetId")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("target_id");

                    b.Property<string>("TargetType")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("target_type");

                    b.Property<ulong?>("UserId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("Action")
                        .HasDatabaseName("idx_audit_action");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("idx_audit_time");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_audit_user");

                    b.ToTable("audit_logs", (string)null);

                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_unicode_ci");
                });

            modelBuilder.Entity("Yf.Api.Infrastructure.Entities.CollaborationRead", b =>
                {
                    b.Property<ulong>("ActivityId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("activity_id");

                    b.Property<ulong>("UserId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("user_id");

                    b.Property<DateTime>("ReadAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(3)")
                        .HasColumnName("read_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(3)");

                    b.HasKey("ActivityId", "UserId");

                    b.HasIndex("UserId", "ActivityId")
                        .HasDatabaseName("idx_collaboration_reads_user_activity");

                    b.ToTable("collaboration_reads", (string)null);

                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_unicode_ci");
                });

            modelBuilder.Entity("Yf.Api.Infrastructure.Entities.Department", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<ulong>("BusinessParentScope")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("business_parent_scope")
                        .HasComputedColumnSql("ifnull(`parent_id`,0)", true);

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)")
                        .HasDefaultValue("DIVISION")
                        .HasColumnName("kind");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("name");

                    b.Property<ulong?>("ParentId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("parent_id");

                    b.Property<int>("SortNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("sort_no");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)")
                        .HasDefaultValue("ACTIVE")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime>("UpdatedAt"));

                    b.HasKey("Id");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("idx_departments_parent");

                    b.HasIndex("BusinessParentScope", "Kind", "Name")
                        .IsUnique()
                        .HasDatabaseName("uk_departments_parent_kind_name");

                    b.ToTable("departments", (string)null);

                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_unicode_ci");
                });

            modelBuilder.Entity("Yf.Api.Infrastructure.Entities.EmailOutbox", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("DedupeKey")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("dedupe_key");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("event_type");

                    b.Property<string>("LastError")
                        .HasMaxLength(1024)
                        .HasColumnType("varchar(1024)")
                        .HasColumnName("last_error");

                    b.Property<DateTime?>("NextAttemptAt")
                        .HasColumnType("datetime(3)")
                        .HasColumnName("next_attempt_at");

                    b.Property<ulong?>("ProjectId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("project_id");

                    b.Property<string>("RecipientEmail")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("recipient_email");

                    b.Property<ulong?>("RecipientUserId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("recipient_user_id");

                    b.Property<int>("RetryCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("retry_count");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("datetime")
                        .HasColumnName("sent_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)")
                        .HasDefaultValue("PENDING")
                        .HasColumnName("status");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("subject");

                    b.HasKey("Id");

                    b.HasIndex("DedupeKey")
                        .IsUnique()
                        .HasDatabaseName("uk_outbox_dedupe_key");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("fk_outbox_project_v2");

                    b.HasIndex("Status", "NextAttemptAt")
                        .HasDatabaseName("idx_outbox_status_next");

                    b.HasIndex("Status", "RetryCount")
                        .HasDatabaseName("idx_outbox_status");

                    b.ToTable("email_outbox", (string)null);

                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_unicode_ci");
                });

            modelBuilder.Entity("Yf.Api.Infrastructure.Entities.FileCopyRef", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<ulong>("CopyId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("copy_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<ulong>("SourceFileId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("source_file_id");

                    b.Property<string>("SourceFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("source_file_name");

                    b.Property<ulong>("TargetFileId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("target_file_id");

                    b.Property<string>("TargetFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("target_file_name");

                    b.HasKey("Id");

                    b.HasIndex("SourceFileId")
                        .HasDatabaseName("idx_file_copy_refs_source");

                    b.HasIndex("TargetFileId")
                        .IsUnique()
                        .HasDatabaseName("uk_file_copy_refs_target");

                    b.HasIndex("CopyId", "Id")
                        .HasDatabaseName("idx_file_copy_refs_copy");

                    b.ToTable("file_copy_refs", (string)null);

                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_unicode_ci");
                });

            modelBuilder.Entity("Yf.Api.Infrastructure.Entities.FileRecord", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(3)")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)")
                        .HasColumnName("direction");

                    b.Property<string>("Ext")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)")
                        .HasColumnName("ext");

                    b.Property<string>("MimeType")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("mime_type");

                    b.Property<string>("OriginalName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("original_name");

                    b.Property<ulong>("ProjectId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("project_id");

                    b.Property<string>("Sha256")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("sha256");

                    b.Property<ulong>("SizeBytes")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("size_bytes");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)")
                        .HasDefaultValue("AVAILABLE")
                        .HasColumnName("status");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)")
                        .HasColumnName("storage_path");

                    b.Property<string>("StoredName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("stored_name");

                    b.Property<ulong>("UploaderId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("uploader_id");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("idx_files_project");

                    b.HasIndex("StoredName")
                        .IsUnique()
                        .HasDatabaseName("stored_name");

                    b.HasIndex("UploaderId")
                        .HasDatabaseName("fk_files_uploader");

                    b.HasIndex("Status", "DeletedAt")
                        .HasDatabaseName("idx_files_status_deleted_at");

                    b.ToTable("files", (string)null);

                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_unicode_ci");
                });

            modelBuilder.Entity("Yf.Api.Infrastructure.Entities.Message", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("deleted_at");

                    b.Property<ulong?>("DeletedBy")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("deleted_by");

                    b.Property<ulong>("ProjectId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("project_id");

                    b.Property<ulong>("SenderId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("sender_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)")
                        .HasDefaultValue("NORMAL")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("SenderId")
                        .HasDatabaseName("fk_msg_sender");

                    b.HasIndex("ProjectId", "CreatedAt")
                        .HasDatabaseName("idx_msg_project_time");

                    b.ToTable("messages", (string)null);

                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_unicode_ci");
                });

            modelBuilder.Entity("Yf.Api.Infrastructure.Entities.MessageImage", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(3)")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(3)");

                    b.Property<string>("Ext")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)")
                        .HasColumnName("ext");

                    b.Property<ulong>("MessageId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("message_id");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("mime_type");

                    b.Property<string>("OriginalName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("original_name");

                    b.Property<ulong>("SizeBytes")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("size_bytes");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)")
                        .HasColumnName("storage_path");

                    b.Property<string>("StoredName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("stored_name");

                    b.HasKey("Id");

                    b.HasIndex("StoredName")
                        .IsUnique()
                        .HasDatabaseName("uk_message_images_stored_name");

                    b.HasIndex("MessageId", "Id")
                        .HasDatabaseName("idx_message_images_message");

                    b.ToTable("message_images", (string)null);

                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_unicode_ci");
                });

            modelBuilder.Entity("Yf.Api.Infrastructure.Entities.MessageRead", b =>
                {
                    b.Property<ulong>("MessageId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("message_id");

                    b.Property<ulong>("UserId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("user_id");

                    b.Property<DateTime>("ReadAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("read_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("MessageId", "UserId");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_mr_user");

                    b.ToTable("message_reads", (string)null);

                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_unicode_ci");
                });

            modelBuilder.Entity("Yf.Api.Infrastructure.Entities.Permission", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("name");

                    b.Property<ulong?>("ParentId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("parent_id");

                    b.Property<int>("SortNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("sort_no");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("code");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("idx_permissions_parent");

                    b.ToTable("permissions", (string)null);

                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_unicode_ci");
                });

            modelBuilder.Entity("Yf.Api.Infrastructure.Entities.Project", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<string>("ConfirmSide")
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)")
                        .HasColumnName("confirm_side");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<ulong>("CreatedBy")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasMaxLength(1024)
                        .HasColumnType("varchar(1024)")
                        .HasColumnName("description");

                    b.Property<DateOnly?>("ExpectedCompletionDate")
                        .HasColumnType("date")
                        .HasColumnName("expected_completion_date");

                    b.Property<string>("MachineModel")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("machine_model");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("name");

                    b.Property<ulong?>("PriorityId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("priority_id");

                    b.Property<ulong>("ProjectGroupId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("project_group_id");

                    b.Property<ulong?>("ResponsibleUserId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("responsible_user_id");

                    b.Property<ulong?>("RobotModelId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("robot_model_id");

                    b.Property<ulong?>("RobotVendorId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("robot_vendor_id");

                    b.Property<ulong?>("SectionId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("section_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(24)
                        .HasColumnType("varchar(24)")
                        .HasDefaultValue("DRAFT")
                        .HasColumnName("status");

                    b.Property<ulong>("SupplierId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("supplier_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime>("UpdatedAt"));

                    b.HasKey("Id");

                    b.HasIndex("ExpectedCompletionDate")
                        .HasDatabaseName("idx_projects_expected_completion");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("uk_projects_name");

                    b.HasIndex("PriorityId")
                        .HasDatabaseName("idx_projects_priority");

                    b.HasIndex("ResponsibleUserId")
                        .HasDatabaseName("idx_projects_responsible_user");

                    b.HasIndex("RobotModelId")
                        .HasDatabaseName("idx_projects_robot_model");

                    b.HasIndex("RobotVendorId")
                        .HasDatabaseName("idx_projects_robot_vendor");

                    b.HasIndex("SectionId")
                        .HasDatabaseName("idx_projects_section");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_projects_status");

                    b.HasIndex("SupplierId")
                        .HasDatabaseName("idx_projects_supplier");

                    b.HasIndex("ProjectGroupId", "Id")
                        .HasDatabaseName("idx_projects_group");

                    b.ToTable("projects", (string)null);

                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_unicode_ci");
                });

            modelBuilder.Entity("Yf.Api.Infrastructure.Entities.ProjectActivity", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("action");

                    b.Property<string>("ActivityType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)")
                        .HasColumnName("activity_type");

                    b.Property<ulong?>("ActorId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("actor_id");

                    b.Property<string>("ActorName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("actor_name");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("datetime(3)")
                        .HasColumnName("occurred_at");

                    b.Property<ulong>("ProjectId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("project_id");

                    b.Property<string>("SourceKey")
                        .IsRequired()
                        .HasMaxLength(191)
                        .HasColumnType("varchar(191)")
                        .HasColumnName("source_key");

                    b.Property<string>("Summary")
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)")
                        .HasColumnName("summary");

                    b.Property<ulong?>("TargetId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("target_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("SourceKey")
                        .IsUnique()
                        .HasDatabaseName("uk_project_activities_source");

                    b.HasIndex("ProjectId", "OccurredAt", "Id")
                        .HasDatabaseName("idx_project_activities_project_time");

                    b.HasIndex("ProjectId", "ActivityType", "OccurredAt", "Id")
                        .HasDatabaseName("idx_project_activities_project_type_time");

                    b.ToTable("project_activities", (string)null);
                });

            modelBuilder.Entity("Yf.Api.Infrastructure.Entities.ProjectCopy", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<ulong>("CopiedBy")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("copied_by");

                    b.Property<string>("CopiedByName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("copied_by_name");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<ulong>("FileCount")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("file_count");

                    b.Property<ulong>("SourceProjectId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("source_project_id");

                    b.Property<string>("SourceProjectName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("source_project_name");

                    b.Property<ulong>("TargetProjectId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("target_project_id");

                    b.Property<string>("TargetProjectName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("target_project_name");

                    b.Property<ulong>("TotalBytes")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("total_bytes");

                    b.HasKey("Id");

                    b.HasIndex("CopiedBy")
                        .HasDatabaseName("idx_project_copies_copied_by");

                    b.HasIndex("TargetProjectId")
                        .IsUnique()
                        .HasDatabaseName("uk_project_copies_target");

                    b.HasIndex("SourceProjectId", "CreatedAt", "Id")
                        .HasDatabaseName("idx_project_copies_source_time");

                    b.ToTable("project_copies", (string)null);

                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_unicode_ci");
                });

            modelBuilder.Entity("Yf.Api.Infrastructure.Entities.ProjectDictionary", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(3)")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(3)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("name");

                    b.Property<ulong?>("ParentId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("parent_id");

                    b.Property<int>("SortNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("sort_no");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)")
                        .HasDefaultValue("ACTIVE")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(3)")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(3)");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime>("UpdatedAt"));

                    b.HasKey("Id");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("idx_project_dictionaries_parent");

                    b.HasIndex("Type", "Name")
                        .IsUnique()
                        .HasDatabaseName("uk_project_dictionaries_type_name");

                    b.HasIndex("Type", "Status", "SortNo", "Id")
                        .HasDatabaseName("idx_project_dictionaries_type_status_sort");

                    b.ToTable("project_dictionaries", (string)null);

                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_unicode_ci");
                });

            modelBuilder.Entity("Yf.Api.Infrastructure.Entities.ProjectGroup", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime(3)")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(3)")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(3)");

                    b.Property<ulong>("CreatedBy")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasMaxLength(1024)
                        .HasColumnType("varchar(1024)")
                        .HasColumnName("description");

                    b.Property<DateOnly?>("ExpectedCompletionDate")
                        .HasColumnType("date")
                        .HasColumnName("expected_completion_date");

                    b.Property<string>("MachineModel")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("machine_model");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("name");

                    b.Property<ulong?>("PriorityId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("priority_id");

                    b.Property<ulong?>("ResponsibleUserId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("responsible_user_id");

                    b.Property<ulong?>("RobotModelId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("robot_model_id");

                    b.Property<ulong?>("RobotVendorId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("robot_vendor_id");

                    b.Property<ulong?>("SectionId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("section_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(24)
                        .HasColumnType("varchar(24)")
                        .HasDefaultValue("DRAFT")
                        .HasColumnName("status");

                    b.Property<ulong>("SupplierId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("supplier_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(3)")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(3)");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime>("UpdatedAt"));

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("fk_project_groups_created_by");

                    b.HasIndex("ExpectedCompletionDate")
                        .HasDatabaseName("idx_project_groups_expected_completion");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("uk_project_groups_name");

                    b.HasIndex("PriorityId")
                        .HasDatabaseName("fk_project_groups_priority");

                    b.HasIndex("ResponsibleUserId")
                        .HasDatabaseName("idx_project_groups_responsible_user");

                    b.HasIndex("RobotModelId")
                        .HasDatabaseName("fk_project_groups_robot_model");

                    b.HasIndex("RobotVendorId")
                        .HasDatabaseName("fk_project_groups_robot_vendor");

                    b.HasIndex("SectionId")
                        .HasDatabaseName("fk_project_groups_section");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_project_groups_status");

                    b.HasIndex("SupplierId")
                        .HasDatabaseName("idx_project_groups_supplier");

                    b.ToTable("project_groups", (string)null);

                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_unicode_ci");
                });

            modelBuilder.Entity("Yf.Api.Infrastructure.Entities.ProjectGroupStatusLog", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("action");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(3)")
                        .HasColumnName("created_at");

                    b.Property<string>("FromStatus")
                        .HasMaxLength(24)
                        .HasColumnType("varchar(24)")
                        .HasColumnName("from_status");

                    b.Property<ulong>("OperatorId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("operator_id");

                    b.Property<ulong>("ProjectGroupId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("project_group_id");

                    b.Property<string>("ToStatus")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("varchar(24)")
                        .HasColumnName("to_status");

                    b.Property<ulong?>("TriggerProjectId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("trigger_project_id");

                    b.HasKey("Id");

                    b.HasIndex("OperatorId")
                        .HasDatabaseName("idx_project_group_status_logs_operator");

                    b.HasIndex("TriggerProjectId")
                        .HasDatabaseName("idx_project_group_status_logs_project");

                    b.HasIndex("ProjectGroupId", "CreatedAt", "Id")
                        .HasDatabaseName("idx_project_group_status_logs_group_time");

                    b.ToTable("project_group_status_logs", (string)null);

                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_unicode_ci");
                });

            modelBuilder.Entity("Yf.Api.Infrastructure.Entities.ProjectGroupWorkOrder", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(3)")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(3)");

                    b.Property<ulong>("ProjectGroupId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("project_group_id");

                    b.Property<int>("SortNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("sort_no");

                    b.Property<string>("WorkOrderNo")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("work_order_no");

                    b.HasKey("Id");

                    b.HasIndex("ProjectGroupId", "WorkOrderNo")
                        .IsUnique()
                        .HasDatabaseName("uk_project_group_work_orders_group_no");

                    b.HasIndex("ProjectGroupId", "SortNo", "Id")
                        .HasDatabaseName("idx_project_group_work_orders_group_sort");

                    b.ToTable("project_group_work_orders", (string)null);

                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_unicode_ci");
                });

            modelBuilder.Entity("Yf.Api.Infrastructure.Entities.ProjectStatusLog", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)")
                        .HasColumnName("action");

                    b.Property<string>("ConfirmSide")
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)")
                        .HasColumnName("confirm_side");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(3)")
                        .HasColumnName("created_at");

                    b.Property<string>("FromStatus")
                        .HasMaxLength(24)
                        .HasColumnType("varchar(24)")
                        .HasColumnName("from_status");

                    b.Property<ulong>("OperatorId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("operator_id");

                    b.Property<ulong>("ProjectId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("project_id");

                    b.Property<string>("Reason")
                        .HasMaxLength(1024)
                        .HasColumnType("varchar(1024)")
                        .HasColumnName("reason");

                    b.Property<string>("ToStatus")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("varchar(24)")
                        .HasColumnName("to_status");

                    b.HasKey("Id");

                    b.HasIndex("OperatorId")
                        .HasDatabaseName("fk_project_status_logs_operator");

                    b.HasIndex("ProjectId", "CreatedAt", "Id")
                        .HasDatabaseName("idx_project_status_logs_project_time");

                    b.ToTable("project_status_logs", (string)null);
                });

            modelBuilder.Entity("Yf.Api.Infrastructure.Entities.ProjectWorkOrder", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(3)")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(3)");

                    b.Property<ulong>("ProjectId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("project_id");

                    b.Property<int>("SortNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("sort_no");

                    b.Property<string>("WorkOrderNo")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("work_order_no");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId", "WorkOrderNo")
                        .IsUnique()
                        .HasDatabaseName("uk_project_work_orders_project_no");

                    b.HasIndex("ProjectId", "SortNo", "Id")
                        .HasDatabaseName("idx_project_work_orders_project_sort");

                    b.ToTable("project_work_orders", (string)null);

                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_unicode_ci");
                });

            modelBuilder.Entity("Yf.Api.Infrastructure.Entities.RefreshToken", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime")
                        .HasColumnName("expires_at");

                    b.Property<string>("Ip")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("ip");

                    b.Property<bool>("Revoked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("revoked");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("session_id");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("token_hash");

                    b.Property<ulong>("UserId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("token_hash");

                    b.HasIndex("UserId")
                        .HasDatabaseName("fk_rt_user");

                    b.HasIndex("SessionId", "UserId", "Revoked", "ExpiresAt")
                        .HasDatabaseName("idx_refresh_tokens_session_state");

                    b.ToTable("refresh_tokens", (string)null);

                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_unicode_ci");
                });

            modelBuilder.Entity("Yf.Api.Infrastructure.Entities.Role", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("description");

                    b.Property<bool>("IsBuiltIn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("is_built_in");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)")
                        .HasDefaultValue("ACTIVE")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime>("UpdatedAt"));

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("uk_roles_name");

                    b.ToTable("roles", (string)null);

                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_unicode_ci");
                });

            modelBuilder.Entity("Yf.Api.Infrastructure.Entities.RolePermission", b =>
                {
                    b.Property<ulong>("RoleId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("role_id");

                    b.Property<ulong>("PermissionId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("permission_id");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId")
                        .HasDatabaseName("fk_rp_perm");

                    b.ToTable("role_permissions", (string)null);

                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_unicode_ci");
                });

            modelBuilder.Entity("Yf.Api.Infrastructure.Entities.Supplier", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<ulong?>("CreatedBy")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("created_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("name");

                    b.Property<string>("Remark")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)")
                        .HasColumnName("remark");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)")
                        .HasDefaultValue("ACTIVE")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime>("UpdatedAt"));

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("uk_suppliers_name");

                    b.ToTable("suppliers", (string)null);

                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_unicode_ci");
                });

            modelBuilder.Entity("Yf.Api.Infrastructure.Entities.SystemConfig", b =>
                {
                    b.Property<string>("CfgKey")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("cfg_key");

                    b.Property<string>("CfgValue")
                        .HasMaxLength(2048)
                        .HasColumnType("varchar(2048)")
                        .HasColumnName("cfg_value");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("description");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime>("UpdatedAt"));

                    b.HasKey("CfgKey");

                    b.ToTable("system_configs", (string)null);

                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_unicode_ci");
                });

            modelBuilder.Entity("Yf.Api.Infrastructure.Entities.UploadSession", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("id");

                    b.Property<uint>("ChunkSize")
                        .HasColumnType("int unsigned")
                        .HasColumnName("chunk_size");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime")
                        .HasColumnName("expires_at");

                    b.Property<string>("FileMd5")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("file_md5");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("file_name");

                    b.Property<ulong>("FileSize")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("file_size");

                    b.Property<ulong>("ProjectId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("project_id");

                    b.Property<ulong?>("ResultFileId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("result_file_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)")
                        .HasDefaultValue("UPLOADING")
                        .HasColumnName("status");

                    b.Property<string>("TempDir")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)")
                        .HasColumnName("temp_dir");

                    b.Property<uint>("TotalChunks")
                        .HasColumnType("int unsigned")
                        .HasColumnName("total_chunks");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime>("UpdatedAt"));

                    b.Property<ulong>("UploaderId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("uploader_id");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("fk_us_project");

                    b.HasIndex("ResultFileId")
                        .HasDatabaseName("idx_upload_result_file");

                    b.HasIndex("UploaderId")
                        .HasDatabaseName("idx_us_uploader");

                    b.HasIndex("Status", "ExpiresAt")
                        .HasDatabaseName("idx_us_status_exp");

                    b.ToTable("upload_sessions", (string)null);

                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_unicode_ci");
                });

            modelBuilder.Entity("Yf.Api.Infrastructure.Entities.User", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<ulong?>("CreatedBy")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("created_by");

                    b.Property<ulong?>("DepartmentId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("department_id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("email");

                    b.Property<string>("EmployeeNo")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("employee_no");

                    b.Property<int>("FailedLoginAttempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("failed_login_attempts");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime")
                        .HasColumnName("last_login_at");

                    b.Property<string>("LastLoginIp")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("last_login_ip");

                    b.Property<DateTime?>("LockedUntil")
                        .HasColumnType("datetime")
                        .HasColumnName("locked_until");

                    b.Property<bool>("MustChangePassword")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("must_change_password");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("RealName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("real_name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)")
                        .HasDefaultValue("ACTIVE")
                        .HasColumnName("status");

                    b.Property<ulong?>("SupplierId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("supplier_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime>("UpdatedAt"));

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)")
                        .HasColumnName("user_type");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId")
                        .HasDatabaseName("idx_users_department");

                    b.HasIndex("EmployeeNo")
                        .IsUnique()
                        .HasDatabaseName("uk_users_employee_no");

                    b.HasIndex("SupplierId")
                        .HasDatabaseName("idx_users_supplier");

                    b.ToTable("users", (string)null);

                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_unicode_ci");
                });

            modelBuilder.Entity("Yf.Api.Infrastructure.Entities.UserRole", b =>
                {
                    b.Property<ulong>("UserId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("user_id");

                    b.Property<ulong>("RoleId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("fk_ur_role");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("uk_user_roles_user_id");

                    b.ToTable("user_roles", (string)null);

                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_unicode_ci");
                });

            modelBuilder.Entity("Yf.Api.Infrastructure.Entities.CollaborationRead", b =>
                {
                    b.HasOne("Yf.Api.Infrastructure.Entities.ProjectActivity", null)
                        .WithMany()
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_collaboration_reads_activity");

                    b.HasOne("Yf.Api.Infrastructure.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_collaboration_reads_user");
                });

            modelBuilder.Entity("Yf.Api.Infrastructure.Entities.EmailOutbox", b =>
                {
                    b.HasOne("Yf.Api.Infrastructure.Entities.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_outbox_project_v2");
                });

            modelBuilder.Entity("Yf.Api.Infrastructure.Entities.FileCopyRef", b =>
                {
                    b.HasOne("Yf.Api.Infrastructure.Entities.ProjectCopy", null)
                        .WithMany()
                        .HasForeignKey("CopyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_file_copy_refs_copy");

                    b.HasOne("Yf.Api.Infrastructure.Entities.FileRecord", null)
                        .WithMany()
                        .HasForeignKey("SourceFileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_file_copy_refs_source");

                    b.HasOne("Yf.Api.Infrastructure.Entities.FileRecord", null)
                        .WithMany()
                        .HasForeignKey("TargetFileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_file_copy_refs_target");
                });

            modelBuilder.Entity("Yf.Api.Infrastructure.Entities.FileRecord", b =>
                {
                    b.HasOne("Yf.Api.Infrastructure.Entities.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_files_project");

                    b.HasOne("Yf.Api.Infrastructure.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UploaderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_files_uploader");
                });

            modelBuilder.Entity("Yf.Api.Infrastructure.Entities.Message", b =>
                {
                    b.HasOne("Yf.Api.Infrastructure.Entities.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_msg_project");

                    b.HasOne("Yf.Api.Infrastructure.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_msg_sender");
                });

            modelBuilder.Entity("Yf.Api.Infrastructure.Entities.MessageImage", b =>
                {
                    b.HasOne("Yf.Api.Infrastructure.Entities.Message", null)
                        .WithMany()
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_message_images_message");
                });

            modelBuilder.Entity("Yf.Api.Infrastructure.Entities.MessageRead", b =>
                {
                    b.HasOne("Yf.Api.Infrastructure.Entities.Message", null)
                        .WithMany()
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_mr_msg");

                    b.HasOne("Yf.Api.Infrastructure.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_mr_user");
                });

            modelBuilder.Entity("Yf.Api.Infrastructure.Entities.Project", b =>
                {
                    b.HasOne("Yf.Api.Infrastructure.Entities.ProjectDictionary", null)
                        .WithMany()
                        .HasForeignKey("PriorityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_projects_priority");

                    b.HasOne("Yf.Api.Infrastructure.Entities.ProjectGroup", null)
                        .WithMany()
                        .HasForeignKey("ProjectGroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_projects_group");

                    b.HasOne("Yf.Api.Infrastructure.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("ResponsibleUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_projects_responsible_user");

                    b.HasOne("Yf.Api.Infrastructure.Entities.ProjectDictionary", null)
                        .WithMany()
                        .HasForeignKey("RobotModelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_projects_robot_model");

                    b.HasOne("Yf.Api.Infrastructure.Entities.ProjectDictionary", null)
                        .WithMany()
                        .HasForeignKey("RobotVendorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_projects_robot_vendor");

                    b.HasOne("Yf.Api.Infrastructure.Entities.Department", null)
                        .WithMany()
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_projects_section");

                    b.HasOne("Yf.Api.Infrastructure.Entities.Supplier", null)
                        .WithMany()
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_projects_supplier");
                });

            modelBuilder.Entity("Yf.Api.Infrastructure.Entities.ProjectActivity", b =>
                {
                    b.HasOne("Yf.Api.Infrastructure.Entities.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_project_activities_project");
                });

            modelBuilder.Entity("Yf.Api.Infrastructure.Entities.ProjectCopy", b =>
                {
                    b.HasOne("Yf.Api.Infrastructure.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("CopiedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_project_copies_copied_by");

                    b.HasOne("Yf.Api.Infrastructure.Entities.Project", null)
                        .WithMany()
                        .HasForeignKey("SourceProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_project_copies_source");

                    b.HasOne("Yf.Api.Infrastructure.Entities.Project", null)
                        .WithMany()
                        .HasForeignKey("TargetProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_project_copies_target");
                });

            modelBuilder.Entity("Yf.Api.Infrastructure.Entities.ProjectDictionary", b =>
                {
                    b.HasOne("Yf.Api.Infrastructure.Entities.ProjectDictionary", null)
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_project_dictionaries_parent");
                });

            modelBuilder.Entity("Yf.Api.Infrastructure.Entities.ProjectGroup", b =>
                {
                    b.HasOne("Yf.Api.Infrastructure.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_project_groups_created_by");

                    b.HasOne("Yf.Api.Infrastructure.Entities.ProjectDictionary", null)
                        .WithMany()
                        .HasForeignKey("PriorityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_project_groups_priority");

                    b.HasOne("Yf.Api.Infrastructure.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("ResponsibleUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_project_groups_responsible_user");

                    b.HasOne("Yf.Api.Infrastructure.Entities.ProjectDictionary", null)
                        .WithMany()
                        .HasForeignKey("RobotModelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_project_groups_robot_model");

                    b.HasOne("Yf.Api.Infrastructure.Entities.ProjectDictionary", null)
                        .WithMany()
                        .HasForeignKey("RobotVendorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_project_groups_robot_vendor");

                    b.HasOne("Yf.Api.Infrastructure.Entities.Department", null)
                        .WithMany()
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_project_groups_section");

                    b.HasOne("Yf.Api.Infrastructure.Entities.Supplier", null)
                        .WithMany()
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_project_groups_supplier");
                });

            modelBuilder.Entity("Yf.Api.Infrastructure.Entities.ProjectGroupStatusLog", b =>
                {
                    b.HasOne("Yf.Api.Infrastructure.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("OperatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_project_group_status_logs_operator");

                    b.HasOne("Yf.Api.Infrastructure.Entities.ProjectGroup", null)
                        .WithMany()
                        .HasForeignKey("ProjectGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_project_group_status_logs_group");

                    b.HasOne("Yf.Api.Infrastructure.Entities.Project", null)
                        .WithMany()
                        .HasForeignKey("TriggerProjectId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_project_group_status_logs_project");
                });

            modelBuilder.Entity("Yf.Api.Infrastructure.Entities.ProjectGroupWorkOrder", b =>
                {
                    b.HasOne("Yf.Api.Infrastructure.Entities.ProjectGroup", null)
                        .WithMany()
                        .HasForeignKey("ProjectGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_project_group_work_orders_group");
                });

            modelBuilder.Entity("Yf.Api.Infrastructure.Entities.ProjectStatusLog", b =>
                {
                    b.HasOne("Yf.Api.Infrastructure.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("OperatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_project_status_logs_operator");

                    b.HasOne("Yf.Api.Infrastructure.Entities.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_project_status_logs_project");
                });

            modelBuilder.Entity("Yf.Api.Infrastructure.Entities.ProjectWorkOrder", b =>
                {
                    b.HasOne("Yf.Api.Infrastructure.Entities.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_project_work_orders_project");
                });

            modelBuilder.Entity("Yf.Api.Infrastructure.Entities.RefreshToken", b =>
                {
                    b.HasOne("Yf.Api.Infrastructure.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_rt_user");
                });

            modelBuilder.Entity("Yf.Api.Infrastructure.Entities.RolePermission", b =>
                {
                    b.HasOne("Yf.Api.Infrastructure.Entities.Permission", null)
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_rp_perm");

                    b.HasOne("Yf.Api.Infrastructure.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_rp_role");
                });

            modelBuilder.Entity("Yf.Api.Infrastructure.Entities.UploadSession", b =>
                {
                    b.HasOne("Yf.Api.Infrastructure.Entities.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_us_project");

                    b.HasOne("Yf.Api.Infrastructure.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UploaderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_us_uploader");
                });

            modelBuilder.Entity("Yf.Api.Infrastructure.Entities.User", b =>
                {
                    b.HasOne("Yf.Api.Infrastructure.Entities.Supplier", null)
                        .WithMany()
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_users_supplier");
                });

            modelBuilder.Entity("Yf.Api.Infrastructure.Entities.UserRole", b =>
                {
                    b.HasOne("Yf.Api.Infrastructure.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_ur_role");

                    b.HasOne("Yf.Api.Infrastructure.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_ur_user");
                });
#pragma warning restore 612, 618
        }
    }
}
