using Dapper;
using MySqlConnector;
using Yf.Api.Infrastructure;
using Yf.Api.Modules.Identity;

namespace Yf.Api.Modules.Admin;

public sealed class SupplierService(AppDb db, AuditService audit)
{
    private const string SupplierSelect = "SELECT id Id,name Name,remark Remark,status Status,created_at CreatedAt FROM suppliers";
    private const string UserSelect = "SELECT id Id,employee_no EmployeeNo,password_hash PasswordHash,real_name RealName,email Email,user_type UserType,supplier_id SupplierId,department_id DepartmentId,status Status,must_change_password MustChangePassword,last_login_at LastLoginAt,created_at CreatedAt FROM users";
    public async Task<object> ListAsync(CurrentUser actor, ulong page, uint size, ulong offset, string? keyword, string? status, CancellationToken ct)
    {
        AccessService.RequireInternal(actor); await using var c = await db.OpenAsync(ct); await AccessService.RequirePermissionAsync(c, null, actor, "supplier:manage", ct); var where = " WHERE 1=1"; if (!string.IsNullOrWhiteSpace(keyword)) where += " AND name LIKE CONCAT('%',@keyword,'%')"; if (!string.IsNullOrWhiteSpace(status)) where += " AND status=@status"; var p = new { keyword = keyword?.Trim(), status, size, offset }; var total = await c.ExecuteScalarAsync<ulong>(new CommandDefinition("SELECT COUNT(*) FROM suppliers" + where, p, cancellationToken: ct)); var rows = await c.QueryAsync<SupplierRow>(new CommandDefinition(SupplierSelect + where + " ORDER BY id DESC LIMIT @size OFFSET @offset", p, cancellationToken: ct)); return new { list = rows.Select(Json).ToArray(), total, page, pageSize = size };
    }
    public async Task<object> DetailAsync(CurrentUser actor, ulong id, CancellationToken ct) { AccessService.RequireInternal(actor); await using var c = await db.OpenAsync(ct); await AccessService.RequirePermissionAsync(c, null, actor, "supplier:manage", ct); return Json(await FindAsync(c, null, id, ct) ?? throw ApiException.NotFound()); }
    public Task<object> CreateAsync(CurrentUser a, SupplierUpsert r, CancellationToken ct) => UpsertAsync(a, null, r, ct);
    public Task<object> UpdateAsync(CurrentUser a, ulong id, SupplierUpsert r, CancellationToken ct) => UpsertAsync(a, id, r, ct);
    private async Task<object> UpsertAsync(CurrentUser actor, ulong? id, SupplierUpsert request, CancellationToken ct)
    {
        Validate(request); await using var c = await db.OpenAsync(ct); await using var t = await AppDb.BeginTransactionAsync(c, ct); await GateAsync(c, t, actor, "supplier:manage", ct); var existing = id.HasValue ? await FindAsync(c, t, id.Value, ct) ?? throw ApiException.NotFound() : null; if (await c.ExecuteScalarAsync<int>(new CommandDefinition("SELECT EXISTS(SELECT 1 FROM suppliers WHERE name=@name AND (@id IS NULL OR id<>@id))", new { name = request.Name.Trim(), id }, t, cancellationToken: ct)) == 1) throw ApiException.Conflict("供应商名称已存在"); ulong resultId;
        if (id is null) { await c.ExecuteAsync(new CommandDefinition("INSERT INTO suppliers(name,remark,status,created_by,created_at,updated_at) VALUES(@name,@remark,'ACTIVE',@actorId,UTC_TIMESTAMP(6),UTC_TIMESTAMP(6))", new { name = request.Name.Trim(), request.Remark, actorId = actor.Id }, t, cancellationToken: ct)); resultId = await c.ExecuteScalarAsync<ulong>(new CommandDefinition("SELECT LAST_INSERT_ID()", transaction: t, cancellationToken: ct)); }
        else { resultId = id.Value; await c.ExecuteAsync(new CommandDefinition("UPDATE suppliers SET name=@name,remark=@remark,updated_at=UTC_TIMESTAMP(6) WHERE id=@id", new { name = request.Name.Trim(), request.Remark, id }, t, cancellationToken: ct)); }
        await audit.WriteAsync(c, t, actor.Id, id is null ? "SUPPLIER_CREATE" : "SUPPLIER_UPDATE", "supplier", resultId, new { oldName = existing?.Name, newName = request.Name.Trim() }, null, ct); var result = Json(await FindAsync(c, t, resultId, ct) ?? throw ApiException.NotFound()); await t.CommitAsync(ct); return result;
    }
    public async Task<object> SetStatusAsync(CurrentUser actor, ulong id, string status, CancellationToken ct)
    {
        status = AdminValidation.Status(status); await using var c = await db.OpenAsync(ct); await using var t = await AppDb.BeginTransactionAsync(c, ct); await AccessService.LockManagementAsync(c, t, ct); actor = await AccessService.RecheckActorAsync(c, t, actor, ct); AccessService.RequireInternal(actor); await AccessService.RequirePermissionAsync(c, t, actor, "supplier:manage", ct); var row = await c.QuerySingleOrDefaultAsync<SupplierRow>(new CommandDefinition(SupplierSelect + " WHERE id=@id FOR UPDATE", new { id }, t, cancellationToken: ct)) ?? throw ApiException.NotFound(); await c.ExecuteAsync(new CommandDefinition("UPDATE suppliers SET status=@status,updated_at=UTC_TIMESTAMP(6) WHERE id=@id", new { status, id }, t, cancellationToken: ct)); await audit.WriteAsync(c, t, actor.Id, "SUPPLIER_STATUS", "supplier", id, new { row.Name, oldStatus = row.Status, newStatus = status }, null, ct); await t.CommitAsync(ct); return new { row.Id, row.Name, row.Remark, Status = status, row.CreatedAt };
    }
    public async Task DeleteAsync(CurrentUser actor, ulong id, CancellationToken ct)
    {
        await using var c = await db.OpenAsync(ct); await using var t = await AppDb.BeginTransactionAsync(c, ct); await GateAsync(c, t, actor, "supplier:manage", ct); await AccessService.RequirePermissionAsync(c, t, actor, "supplier:delete", ct); var row = await FindAsync(c, t, id, ct) ?? throw ApiException.NotFound(); if (await c.ExecuteScalarAsync<int>(new CommandDefinition("SELECT EXISTS(SELECT 1 FROM projects WHERE supplier_id=@id)", new { id }, t, cancellationToken: ct)) == 1) throw ApiException.BadRequest("该供应商仍有关联项目，请先删除项目"); var accounts = await c.ExecuteScalarAsync<int>(new CommandDefinition("SELECT COUNT(*) FROM users WHERE user_type='SUPPLIER' AND supplier_id=@id", new { id }, t, cancellationToken: ct)); if (accounts > 0) throw ApiException.BadRequest($"该供应商仍有 {accounts} 个账号，请先逐个处理账号"); await audit.WriteAsync(c, t, actor.Id, "SUPPLIER_DELETE", "supplier", id, new { row.Name, accountCount = 0 }, null, ct); await c.ExecuteAsync(new CommandDefinition("DELETE FROM suppliers WHERE id=@id", new { id }, t, cancellationToken: ct)); await t.CommitAsync(ct);
    }
    public async Task<object> AccountsAsync(CurrentUser actor, ulong supplierId, CancellationToken ct)
    {
        AccessService.RequireInternal(actor); await using var c = await db.OpenAsync(ct); await AccessService.RequirePermissionAsync(c, null, actor, "supplier:account", ct); if (await FindAsync(c, null, supplierId, ct) is null) throw ApiException.NotFound(); var rows = await c.QueryAsync<AdminUserRow>(new CommandDefinition(UserSelect + " WHERE user_type='SUPPLIER' AND supplier_id=@supplierId ORDER BY id", new { supplierId }, cancellationToken: ct)); return rows.Select(AccountJson).ToArray();
    }
    public async Task<object> CreateAccountAsync(CurrentUser actor, ulong supplierId, SupplierAccountCreate request, CancellationToken ct)
    {
        AccessService.RequireInternal(actor); AdminValidation.EmployeeNo(request.EmployeeNo); ValidateName(request.RealName); AdminValidation.Email(request.Email); PasswordService.Validate(request.Password); await using var c = await db.OpenAsync(ct); await using var t = await AppDb.BeginTransactionAsync(c, ct); await GateAsync(c, t, actor, "supplier:account", ct); var supplier = await FindAsync(c, t, supplierId, ct) ?? throw ApiException.NotFound(); if (supplier.Status != "ACTIVE") throw ApiException.BadRequest("供应商已被禁用"); if (await c.ExecuteScalarAsync<int>(new CommandDefinition("SELECT EXISTS(SELECT 1 FROM users WHERE employee_no=@eno)", new { eno = request.EmployeeNo.Trim() }, t, cancellationToken: ct)) == 1) throw ApiException.Conflict("工号已存在"); var role = await ActiveSupplierRoleAsync(c, t, ct); var hash = await PasswordService.HashAsync(request.Password, ct);
        await c.ExecuteAsync(new CommandDefinition("INSERT INTO users(employee_no,password_hash,real_name,email,user_type,supplier_id,department_id,status,must_change_password,failed_login_attempts,locked_until,last_login_at,last_login_ip,created_by,created_at,updated_at) VALUES(@eno,@hash,@name,@email,'SUPPLIER',@supplierId,NULL,'ACTIVE',1,0,NULL,NULL,NULL,@actorId,UTC_TIMESTAMP(6),UTC_TIMESTAMP(6))", new { eno = request.EmployeeNo.Trim(), hash, name = request.RealName.Trim(), email = request.Email.Trim(), supplierId, actorId = actor.Id }, t, cancellationToken: ct)); var id = await c.ExecuteScalarAsync<ulong>(new CommandDefinition("SELECT LAST_INSERT_ID()", transaction: t, cancellationToken: ct)); await c.ExecuteAsync(new CommandDefinition("INSERT INTO user_roles(user_id,role_id) VALUES(@id,@roleId)", new { id, roleId = role.Id }, t, cancellationToken: ct)); await audit.WriteAsync(c, t, actor.Id, "SUPPLIER_ACCOUNT_CREATE", "user", id, new { employeeNo = request.EmployeeNo.Trim(), supplierId, roleId = role.Id, roleName = role.Name }, null, ct); var result = AccountJson(await FindAccountAsync(c, t, id, ct) ?? throw ApiException.NotFound()); await t.CommitAsync(ct); return result;
    }
    public async Task<object> UpdateAccountAsync(CurrentUser actor, ulong id, SupplierAccountUpdate request, CancellationToken ct)
    {
        AccessService.RequireInternal(actor); if (request.RealName is not null) ValidateName(request.RealName); if (request.Email is not null) AdminValidation.Email(request.Email); await using var c = await db.OpenAsync(ct); await using var t = await AppDb.BeginTransactionAsync(c, ct); await GateAsync(c, t, actor, "supplier:account", ct); var u = await FindAccountAsync(c, t, id, ct) ?? throw ApiException.NotFound(); await c.ExecuteAsync(new CommandDefinition("UPDATE users SET real_name=COALESCE(@name,real_name),email=COALESCE(@email,email),updated_at=UTC_TIMESTAMP(6) WHERE id=@id", new { name = request.RealName?.Trim(), email = request.Email?.Trim(), id }, t, cancellationToken: ct)); await audit.WriteAsync(c, t, actor.Id, "SUPPLIER_ACCOUNT_UPDATE", "user", id, new { u.EmployeeNo, changedFields = new[] { request.RealName is null ? null : "realName", request.Email is null ? null : "email" }.Where(x=>x is not null) }, null, ct); var result = AccountJson(await FindAccountAsync(c, t, id, ct) ?? throw ApiException.NotFound()); await t.CommitAsync(ct); return result;
    }
    public async Task<object> SetAccountStatusAsync(CurrentUser actor, ulong id, string status, CancellationToken ct)
    {
        AccessService.RequireInternal(actor); status = AdminValidation.Status(status); await using var c = await db.OpenAsync(ct); await using var t = await AppDb.BeginTransactionAsync(c, ct); await AccessService.LockManagementAsync(c, t, ct); actor = await AccessService.RecheckActorAsync(c, t, actor, ct); AccessService.RequireInternal(actor); await AccessService.RequirePermissionAsync(c, t, actor, "supplier:account", ct); var u = await c.QuerySingleOrDefaultAsync<AdminUserRow>(new CommandDefinition(UserSelect + " WHERE id=@id FOR UPDATE", new { id }, t, cancellationToken: ct)) ?? throw ApiException.NotFound(); if (u.UserType != "SUPPLIER") throw ApiException.BadRequest("该账号不是供应商人员"); if (status == "ACTIVE") await EnsureActiveSupplierRoleAssignedAsync(c, t, id, ct); await c.ExecuteAsync(new CommandDefinition("UPDATE users SET status=@status,updated_at=UTC_TIMESTAMP(6) WHERE id=@id", new { status, id }, t, cancellationToken: ct)); if (status == "DISABLED") await IdentityService.RevokeAllAsync(c, t, id, ct); await audit.WriteAsync(c, t, actor.Id, "SUPPLIER_ACCOUNT_STATUS", "user", id, new { u.EmployeeNo, oldStatus = u.Status, newStatus = status, sessionsRevoked = status == "DISABLED" }, null, ct); var result = AccountJson(await FindAccountAsync(c, t, id, ct) ?? throw ApiException.NotFound()); await t.CommitAsync(ct); return result;
    }
    public async Task ResetAccountPasswordAsync(CurrentUser actor, ulong id, string password, CancellationToken ct)
    {
        AccessService.RequireInternal(actor); PasswordService.Validate(password); await using var c = await db.OpenAsync(ct); await using var t = await AppDb.BeginTransactionAsync(c, ct); await GateAsync(c, t, actor, "supplier:account", ct); var u = await FindAccountAsync(c, t, id, ct) ?? throw ApiException.NotFound(); var hash = await PasswordService.HashAsync(password, ct); await c.ExecuteAsync(new CommandDefinition("UPDATE users SET password_hash=@hash,must_change_password=1,failed_login_attempts=0,locked_until=NULL,updated_at=UTC_TIMESTAMP(6) WHERE id=@id", new { hash, id }, t, cancellationToken: ct)); await IdentityService.RevokeAllAsync(c, t, id, ct); await audit.WriteAsync(c, t, actor.Id, "SUPPLIER_ACCOUNT_RESET_PASSWORD", "user", id, new { u.EmployeeNo, sessionsRevoked = true, mustChangePassword = true }, null, ct); await t.CommitAsync(ct);
    }
    public async Task DeleteAccountAsync(CurrentUser actor, ulong id, CancellationToken ct)
    {
        AccessService.RequireInternal(actor); await using var c = await db.OpenAsync(ct); await using var t = await AppDb.BeginTransactionAsync(c, ct); await AccessService.LockManagementAsync(c, t, ct); actor = await AccessService.RecheckActorAsync(c, t, actor, ct); AccessService.RequireInternal(actor); await AccessService.RequirePermissionAsync(c, t, actor, "supplier:account", ct); await AccessService.RequirePermissionAsync(c, t, actor, "supplier:account_delete", ct); var u = await c.QuerySingleOrDefaultAsync<AdminUserRow>(new CommandDefinition(UserSelect + " WHERE id=@id FOR UPDATE", new { id }, t, cancellationToken: ct)) ?? throw ApiException.NotFound(); if (u.UserType != "SUPPLIER") throw ApiException.BadRequest("该账号不是供应商人员"); await UserService.EnsureNoHistoryAsync(c, t, id, ct); await audit.WriteAsync(c, t, actor.Id, "SUPPLIER_ACCOUNT_DELETE", "user", id, new { u.EmployeeNo }, null, ct); await UserService.RemoveAsync(c, t, id, ct); await t.CommitAsync(ct);
    }
    private static async Task GateAsync(MySqlConnection c, MySqlTransaction t, CurrentUser a, string p, CancellationToken ct) { await AccessService.LockManagementAsync(c, t, ct); a = await AccessService.RecheckActorAsync(c, t, a, ct); AccessService.RequireInternal(a); await AccessService.RequirePermissionAsync(c, t, a, p, ct); }
    private static async Task<RoleRow> ActiveSupplierRoleAsync(MySqlConnection c, MySqlTransaction t, CancellationToken ct)
    {
        var role = await c.QuerySingleOrDefaultAsync<RoleRow>(new CommandDefinition("SELECT id Id,name Name,status Status FROM roles WHERE is_built_in=1 AND name='供应商人员'", transaction: t, cancellationToken: ct))
                   ?? throw new InvalidOperationException("内置供应商角色缺失");
        if (role.Status != "ACTIVE") throw ApiException.BadRequest("内置供应商角色已禁用，请先启用该角色");
        return role;
    }
    private static async Task EnsureActiveSupplierRoleAssignedAsync(MySqlConnection c, MySqlTransaction t, ulong userId, CancellationToken ct)
    {
        if (await c.ExecuteScalarAsync<int>(new CommandDefinition("SELECT EXISTS(SELECT 1 FROM user_roles ur JOIN roles r ON r.id=ur.role_id WHERE ur.user_id=@userId AND r.is_built_in=1 AND r.name='供应商人员' AND r.status='ACTIVE')", new { userId }, t, cancellationToken: ct)) != 1)
            throw ApiException.BadRequest("供应商账号未绑定启用的内置供应商角色");
    }
    private static Task<SupplierRow?> FindAsync(MySqlConnection c, MySqlTransaction? t, ulong id, CancellationToken ct) => c.QuerySingleOrDefaultAsync<SupplierRow>(new CommandDefinition(SupplierSelect + " WHERE id=@id", new { id }, t, cancellationToken: ct));
    private static async Task<AdminUserRow?> FindAccountAsync(MySqlConnection c, MySqlTransaction? t, ulong id, CancellationToken ct) { var u = await c.QuerySingleOrDefaultAsync<AdminUserRow>(new CommandDefinition(UserSelect + " WHERE id=@id", new { id }, t, cancellationToken: ct)); if (u is not null && u.UserType != "SUPPLIER") throw ApiException.BadRequest("该账号不是供应商人员"); return u; }
    private static object Json(SupplierRow s) => new { s.Id, s.Name, s.Remark, s.Status, s.CreatedAt };
    private static object AccountJson(AdminUserRow u) => new { u.Id, u.EmployeeNo, u.RealName, u.Email, u.SupplierId, u.Status, u.LastLoginAt, u.CreatedAt };
    private static void Validate(SupplierUpsert r) { if (string.IsNullOrWhiteSpace(r.Name)) throw ApiException.BadRequest("供应商名称不能为空"); if (r.Name.Trim().EnumerateRunes().Count() > 64) throw ApiException.BadRequest("供应商名称过长"); if (r.Remark?.EnumerateRunes().Count() > 500) throw ApiException.BadRequest("备注过长"); }
    private static void ValidateName(string v) { if (string.IsNullOrWhiteSpace(v) || v.Trim().EnumerateRunes().Count() > 32) throw ApiException.BadRequest("姓名需为 1~32 个字符"); }
}
